// WEA_Web/react/bookshop/src/components/BookDetails.jsx
﻿import {useEffect, useState} from "react";
import {baseUrl, getBookById, getBooks} from "../api/bookApi.js";
import {useNavigate, useParams} from "react-router-dom";


function BookDetails(/*props*/) {

    // const { book, onBackClick } = props;

    const [book, setBook] = useState({});
    const params = useParams();
    const navigate = useNavigate();


    useEffect(() => {
        let isActive = true;
        getBookById(params.bookId).then(data => setBook(data.book));
        return () => { isActive = false; }
    }, [params.bookId]);

    function onBackClick() {
        navigate("/books");
    }

    if(!book) {
        return <h1>Loading...</h1>;
    }


    return (
        <div>
            <div className="ui padded grid">
                <div className="four wide column">
                    <img className="ui large image" src={`${baseUrl}/${book.picture}`} alt="Book Cover" />
                </div>
                <div className="eight wide column">
                    <h1 className="ui header">{book.title}</h1>
                    <h3 className="ui header">{book.author}</h3>
                    <div className="ui divider"></div>
                    <div className="ui grid">
                        <div className="four wide column">
                            <h4 className="ui header">Preis</h4>
                            {book.price} €
                        </div>
                        <div className="four wide column">
                            <h4 className="ui header">Erschienen</h4>
                            {book.year}
                        </div>
                    </div>
                </div>
                <div className="sixteen wide column">
                    <h3 className="ui header">Beschreibung</h3>
                    {book.description}
                </div>

            </div>
            <button className="ui red button" onClick={onBackClick}>Zurück zur Buchliste</button>
        </div>
    );
}

export default BookDetails;

// WEA_Web/BookShop/src/app/book-details/book-details.component.ts
import { CommonModule } from '@angular/common';
import {Component, Input, OnInit, output} from '@angular/core';
import { Book } from '../shared/book';
import {BookStoreService} from '../shared/book-store.service';
import {ActivatedRoute, Router} from '@angular/router';

@Component({
  selector: 'wea5-book-details',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './book-details.component.html',
  styles: ``
})
export class BookDetailsComponent implements OnInit{
  @Input() book: Book = new Book();
  // showListEvent = output();  // @Output / EventEmitter

  constructor(public bookStoreService: BookStoreService,
              private route: ActivatedRoute,
              private router: Router) {
  }

  ngOnInit() {
    const params = this.route.snapshot.params;
    // this.book = this.bookStoreService.getBookById(params['id']);
    this.bookStoreService.getBookById(params['id']).subscribe(book => this.book = book);
  }

  showBookList() {
    // this.showListEvent.emit();
    this.router.navigateByUrl('/books');
  }
}

@if (book()) {
    <div class="ui grid">
        <div class="four wide column">
          @if(book().picture) {
            <img class="ui large image" [src]="imageUrl()" alt="{{ book().title }}" />
          }
        </div>
        <div class="eight wide column">
          <h1 class="ui header">{{ book().title }}</h1>
          <h3 class="ui header">{{ book().author }}</h3>
          <div class="ui divider"></div>
          <div class="ui grid">
            <div class="four wide column">
              <h4 class="ui header">Preis</h4>
              {{ book().price }}
            </div>
            <div class="four wide column">
              <h4 class="ui header">Erschienen</h4>
              {{ book().year }}
            </div>
            <div class="four wide column">
              <h4 class="ui header">ISBN</h4>
              {{ book().isbn }}
            </div>
          </div>
        </div>
        <div class="sixteen wide column">
          <h3 class="ui header">Beschreibung</h3>
          {{ book().description }}
        </div>
      </div>

      <button (click)="showBookList()" class="ui red button">Zurück zur Buchliste</button>

      @if (book()) {
        <a class="ui tiny yellow labeled icon button"
          [routerLink]="['../../adminR', book().id]">
          <i class="write icon"></i> Buch bearbeiten
        </a>
      }

      <button (click)="addToShoppingCart()" class="ui tiny green labeled icon button">
        <i class="shop icon"></i> In den Warenkorb legen
      </button>
      (Currently {{totalPrice()}} € in Warenkorb)

}
