// WEA_Web/BookShop/src/app/book-list-item/book-list-item.component.ts
import { Component, Input, input } from '@angular/core';
import { Book } from '../shared/book';

@Component({
  selector: 'a.wea5-book-list-item',
  standalone: true,
  imports: [],
  templateUrl: './book-list-item.component.html',
  styles: ``
})
export class BookListItemComponent {
  //@Input() book: Book = new Book();
  book = input.required<Book>();

}


@if (book().picture) {
    <img class="ui tiny image" [src]="imageUrl()" alt="{{ book().title }}" />
}

<div class="content">
    <div class="header">{{ book().title }}</div>
    <div class="description"> {{ book().author }} </div>
    <div class="extra">Year {{ book().year }}</div>
</div>

// WEA_Web/react/bookshop/src/components/BookListItem.jsx
﻿import {baseUrl} from "../api/bookApi.js";


function BookListItem(props) {
    const book = props.theBook;

    return (
        <>
            <img className="ui tiny image"
                 src={`${baseUrl}/${props.theBook.picture}`}
                 alt="Book Cover" />

            <div className="content">
                <div className="header">{book.title}</div>
                <div className="description">{book.author}</div>
                <div className="extra">Year {book.year}</div>
            </div>
        </>
    )
}

export default BookListItem;
