// WEA_Web/UE01/BookShop/src/app/home/home.component.ts
import { Component } from '@angular/core';
import {RouterLink} from '@angular/router';

@Component({
  selector: 'wea5-home',
  standalone: true,
  imports: [
    RouterLink
  ],
  template: `
    <h1>Home</h1>
    <p>Willkommen im WEA5 BookShop.</p>
    <a routerLink="../books" class="ui red button">
      Buchliste ansehen
      <i class="right arrow icon"></i>
    </a>
  `,
  styles: ``
})
export class HomeComponent {

}

// WEA_Web/react/bookshop/src/components/Home.jsx
﻿import {Link} from "react-router-dom";


function Home() {
  return (
    <div className="ui container">
        <h1>Home</h1>
        <p>Welcome to our Bookstore</p>

        <Link className="ui red button" to="/books">
            Buchliste ansehen
            <i className="right arrow icon"></i>
        </Link>
    </div>
  );
}

export default Home;
