// WEA_Web/BookShop/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { SearchComponent } from "../search/search.component";
import { Book } from '../shared/book';

@Component({
  selector: 'wea5-home',
  standalone: true,
  imports: [RouterLink, SearchComponent],
  template: `
    <div class="ui container two column grid">

    <div class="ui container column">
      <h1>Home</h1>
        <p>Willkommen im WEA5 BookShop.</p>
        <a routerLink="../books" class="ui red button">
      Buchliste ansehen
      <i class="right arrow icon"></i>
      </a>
    </div>

    </div>
  `,
  styles: ``
})
export class HomeComponent {

  constructor(private router: Router, private route: ActivatedRoute) {}

  bookSelected(book: Book) {
    this.router.navigate(['../books', book.id], { relativeTo: this.route });
  }

}

// WEA_Web/react/bookshop/src/components/Home.jsx
﻿import {Link} from "react-router-dom";


function Home() {
  return (
    <div className="ui container">
        <h1>Home</h1>
        <p>Welcome to our Bookstore</p>

        <Link className="ui red button" to="/books">
            Buchliste ansehen
            <i className="right arrow icon"></i>
        </Link>
    </div>
  );
}

export default Home;
