// WEA_Web/react/bookshop/src/components/BookList.jsx
import BookListItem from "./BookListItem.jsx";
import {getBooks} from "../api/bookApi.js";



function BookList(props) {
    const { onBookClick } = props;  // const onBookClick = props.onBookClick;

    const books = getBooks();

/*    const bookItems = [];
    for (const book of books) {
        bookItems.push(
            <div key={book.id} className="item" onClick={() => onBookClick(book)}>
                <div className="content">
                    <div className="header">{book.title}</div>
                    <div className="description">{book.author}</div>
                    <div className="extra">Year {book.year}</div>
                </div>
            </div>
        )
    }*/

    return (
        <div className="ui middle aligned selection divided list">
            {
                books.map(book => (
                    <div key={book.id} className="item" onClick={() => onBookClick(book)}>
                        <BookListItem theBook={book} />
                    </div>
                ))
                // bookItems
            }
        </div>
    )
}


export default BookList;

// WEA_Web/UE01/BookShop/src/app/book-list/book-list.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Book } from '../shared/book';
import { BookListItemComponent } from '../book-list-item/book-list-item.component';
import {BookStoreService} from '../shared/book-store.service';

@Component({
  selector: 'wea5-book-list',
  standalone: true,
  imports: [BookListItemComponent],
  templateUrl: './book-list.component.html',
  styles: ``
})
export class BookListComponent implements OnInit {

  books: Book[] = [];

  @Output() showDetailsEvent = new EventEmitter<Book>();

  constructor(public bookStoreService: BookStoreService) {
  }

  showDetails(book: Book) {
    this.showDetailsEvent.emit(book);
  }

  ngOnInit(): void {
    this.books = this.bookStoreService.getAll();
  }

}

<div class="ui middle aligned selection divided list">
    <a class="item" *ngFor="let book of books">
        <div class="content">
            <div class="header">{{ book.title }}</div>
            <div class="description">{{ book.author }}</div>
            <div class="extra">Year {{ book.year}}</div>
        </div>
    </a>
</div>
